name: api_client
description: API client for Flutter to communicate with the web-api
version: 0.0.1
homepage:

environment:
  sdk: ">=3.1.2"

dependencies:
  audioplayers: ^1.1.1
  connectivity: ^3.0.6
  flutter:
    sdk: flutter
  http: ^0.13.5
  path: ^1.8.2
  path_provider: ^2.0.11
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  sqflite: ^2.2.0+3
  sqflite_common: ^2.4.0+2
  sqflite_common_ffi: ^2.2.0+1
  tuple: ^2.0.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
